language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - 2.0.0
 - rbx-18mode
 - rbx-19mode
 - ruby-head
env:
 - "rake=0.9"
script: "bundle exec rspec -c"
before_install:
 - travis/before_install.sh
before_script:
 - travis/before_script.sh
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-18mode
    - rvm: ruby-head
